import 'dart:io';
import 'dart:typed_data';
import 'package:flutter_email_sender/flutter_email_sender.dart';
import 'package:path_provider/path_provider.dart';
import '../models/users.dart';

class ReportingService {
  static const String _reportEmail = 'b0eschex@gmail.com';

  static Future<bool> sendReport({
    required AppUser reporter,
    required AppUser reportedUser,
    required String message,
    List<Uint8List>? screenshots,
  }) async {
    try {
      final List<String> attachments = [];

      if (screenshots != null && screenshots.isNotEmpty) {
        final tempDir = await getTemporaryDirectory();
        for (int i = 0; i < screenshots.length; i++) {
          final file = File('${tempDir.path}/screenshot_$i.png');
          await file.writeAsBytes(screenshots[i]);
          attachments.add(file.path);
        }
      }

      final Email email = Email(
        body: _buildEmailBody(reporter, reportedUser, message),
        subject: 'User Report - ${reportedUser.displayName}',
        recipients: [_reportEmail],
        attachmentPaths: attachments,
        isHTML: false,
      );

      await FlutterEmailSender.send(email);

      for (final path in attachments) {
        final file = File(path);
        if (await file.exists()) {
          await file.delete();
        }
      }

      return true;
    } catch (e) {
      return false;
    }
  }

  static String _buildEmailBody(
    AppUser reporter,
    AppUser reportedUser,
    String message,
  ) {
    return '''
GIGHUB USER REPORT

Report Details:
==============

Reported User:
- Name: ${reportedUser.displayName}
- ID: ${reportedUser.id}
- User Type: ${reportedUser is DJ ? 'DJ' : 'Booker'}

Reporter:
- Name: ${reporter.displayName}
- ID: ${reporter.id}
- User Type: ${reporter is DJ ? 'DJ' : 'Booker'}

Report Message:
===============
$message

Report Timestamp: ${DateTime.now().toIso8601String()}

---
This report was automatically generated by the GigHub app.
''';
  }
}
