name: gig_hub
description: "this is gighub"
publish_to: 'none'
version: 1.0.21

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

# --- APP BOOTSTRAP ---
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

# --- UI & VISUALS ---
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  flutter_rating_stars: ^1.1.0
  flutter_image_slideshow: ^0.1.6
  pinch_zoom: ^2.0.1
  shimmer: ^3.0.0
  liquid_glass_renderer: ^0.1.1-dev.10
  
# --- AUDIO & MEDIA ---
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.8
  just_waveform: ^0.0.7
  image: ^4.5.4
  cached_network_image: ^3.4.1
  flutter_blurhash: ^0.9.1

# --- DATA & STORAGE ---
  path_provider: ^2.0.0
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  blurhash_dart: ^1.2.1

# --- NETWORK & UTILS ---
  http: ^1.4.0
  flutter_dotenv: ^5.2.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  intl: ^0.20.2
  provider: ^6.1.5
  mailer: ^6.1.0
  flutter_email_sender: ^6.0.3
  geolocator: ^12.0.0

# --- FIREBASE & AUTH ---
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.2
  firebase_storage: ^12.4.9
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^6.1.3

# --- LINKS & NAVIGATION ---
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  flutter_localization: ^0.3.3
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0
  firebase_performance: ^0.10.1+10
  
  
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: '#000000'

flutter_native_splash:
  background_image: "assets/images/blackscreen_splash.png"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/splash_logo.png"
    icon_background_color: '#000000'
    color: '#000000'